### ISSUE TITLE
Add the summary of "Principles of Deep Learning Theory" to the curriculum

### ISSUE THREAD

**Issue by leventov** [jacobhilton/deep_learning_curriculum#7]
Book website: https://deeplearningtheory.com/

A link to the summary is in this post: https://www.lesswrong.com/posts/nRu92PXLrdwqdtQmn/more-recent-progress-in-the-theory-of-neural-networks-1

**Comment by jacobhilton** [comment]
Thanks for the suggestion! I think I'm inclined to agree with [this commenter](https://www.lesswrong.com/posts/nRu92PXLrdwqdtQmn/more-recent-progress-in-the-theory-of-neural-networks-1?commentId=MgF2rY38eLzgzPagt), but maybe I'll add a link to this where I mention NTK.

**Comment by leventov** [comment]
I don't understand the arguments of either Lucius Bushnaq or Dan Roberts and Sho Yaida (the book authors). From the perspective of a non-expert, the discussion seems to have been "won" by the book authors, because their comments are upvoted, and the comments of Lucius Bushnaq are downvoted. So it might be valuable if you weighed in there and described why you agree with Lucius Bushnaq.

**Comment by jacobhilton** [comment]
I decided not to add this in the end, as I think it's a bit too advanced/tangential, but thanks again for suggesting.
